#!/bin/bash

cp -u ./bin/UPDATE-SuperSU.zip  ../vendor/aicp/prebuilt/common
cp -u ./bin/99SuperSUDaemon  ../vendor/aicp/prebuilt/common/etc/init.d

cd ..

COUNT=0
CURRENT_DIR="$PWD"
PD="build_tools/patches"
PATCHES=(
'frameworks/av			frameworks_av.patch'
'frameworks/base		frameworks_base.patch'
'frameworks/native		frameworks_native.patch'
'frameworks/opt/telephony	frameworks_opt_telephony.patch'
'hardware/broadcom/libbt	hardware_broadcom_libbt.patch'
'packages/apps/AicpExtras	packages_apps_AicpExtras.patch'
'packages/inputmethods/LatinIME packages_inputmethods_LatinIME.patch'
'packages/services/Telephony	packages_services_Telephony.patch'
'system/core			system_core.patch'
'vendor/aicp			vendor_aicp.patch'
'build 			build.patch'
'packages/apps/Settings 	packages_apps_Settings.patch'
)

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Patching "$FOLDER" ...
	git apply "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
done
